---

- hosts: web
  become: yes
  tasks:
    - name: Updating
      apt: 
        update_cache: yes
        upgrade: yes

    - name: Requirements installing
      apt:
        name:
          python3-pip
          python3-venv
          git
          nginx
        state: present

    - name: Gearbox_cloning
      git:
        repo: "https://github.com/borssmit/gearbox.git"
        dest: /home/ubuntu/gearbox
        version: main

    - name: Python's_reqirements_installation
      command: pip install -r /home/ubuntu/gearbox/requirements.txt chdir= /home/ubuntu/gearbox

    - name: Django_running
      command: nohup pytho3 manage.py runserver 0.0.0.0:8000 &
      args:
        chdir: /home/ubuntu/gearbox
