---
- hosts: web
  become: yes

  tasks:
    - name: update_system
      apt:
        update_cache: yes
        upgrade: yes

    - name: requirements
      apt:
        name:
          - python3-pip
          - python3-venv
          - git
          - nginx
        state: present

    - name: django cloning
      git:
        repo: "https://github.com/borssmit/gearbox.git"
        dest: /home/ubuntu/gearbox
        version: main

    - name: Create venv
      command: python3 -m venv venv
      args:
        chdir: /home/ubuntu/gearbox  

    - name: Install requirements inside venv
      command: ./venv/bin/pip install -r requirements.txt
      args:
        chdir: /home/ubuntu/gearbox


    # - name: Python req
    #   command: pip install -r requirements.txt
    #   args:
    #     chdir: /home/ubuntu/gearbox

    - name: run django inside venv
      shell: |
        nohup ./venv/bin/python manage.py runserver 0.0.0.0:8000 > django.log 2>&1 &
      args:
        chdir: /home/ubuntu/gearbox


    - name: settings Nginx as reverse proxy
      copy:
        dest: /etc/nginx/sites-available/django.conf
        content: |
          server {
              listen 80;
              server_name _;

              location / {
                  proxy_pass http://127.0.0.1:8000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              }
          }

    - name: activ Nginx
      file:
        src: /etc/nginx/sites-available/django.conf
        dest: /etc/nginx/sites-enabled/django.conf
        state: link
        force: yes

    - name: del def Nginx
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: rerun Nginx
      service:
        name: nginx
        state: restarted
